import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import Header from "@/components/layout/header/header";
import { ProgressBar } from "@/components/ui/page-progress";
export const metadata: Metadata = {
  title: "GDG RBU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased relative`}>
        <ProgressBar className="page-progress">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="w-dvw h-dvh max-w-[1600px] mx-auto border-x overflow-x-hidden relative">
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </ProgressBar>
      </body>
    </html>
  );
}
